# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5d716d686258608f5b1d8a94271751fc772f611b2d8ccae07115a5ae96d9588c92110e003d03458ac65f493a93cdb3438e99edfdb2d6bc19a59650c3d3cdb4

test:
  secret_key_base: d6af74864e3795da5d8a52291d2623ef79398355fbbd38a4f301e209155cc2314c71f0b378476d10e2976bde9eb1a8cb3a19915e9d6b54692689a61d37a1b42b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
